// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatGptWeb
{
    internal sealed partial class Vsix
    {
        public const string Id = "ChatGptWeb.837fc3e6-f2b0-4cea-b503-2510fb8c5f8f";
        public const string Name = "ChatGptWeb";
        public const string Description = @"An  Extension for chagpt web window.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma HKS";
        public const string Tags = "";
    }
}
